language:
    - objective-c

env:
    matrix:
        - python=2.7
        #- python=3.3 CONDA_PY=33
        #- python=3.4 CONDA_PY=34

    global:
        - secure: "Vq+0tW6K4QmoIxvipfTcK1O7iisa8gu8PFf/k5rEAWCUEjdjp+HvjMIP9RvFvbciGCYmOwXl7jny24K+DGOgO4qpXA42TtUvj6aS2kmGYe6BuXF3vQlHR1Ci9MTPAqMGOgg/F6p+8HZgQdnqd5bVqcmt25ZuXf+aNpFltTINl4Z93BRwG8NsGIIX483F135Bv2/OpZc+gcjULUM7G/gOugogpOjBztgKp9kbuHB+5/GxtUhdMeFwbFbGCLzmDRg1akp6YPaWzEtSPrt/44hRixnTFbiypbzC3EhZ3dAElDA+Be44Q+vIhoEAmXZQ36Vr+1JHSWiQfbLcIqoinNHiwTU6PT+fidpfoz6L/ughJhDZ2vJLb8+90lMz3Ue/zZjR4cYCSQktVD2swYSGrxa1VDwAMgKtaUBhzyFQFM+L5x4RdVFOR1O/mjS/opXc5tPVHFypqpFRQ8PxclmzgKKHcBbeXwzUaQK9hxrglNna1fDpjYUhkilWClQtJYYE7oeCTqWdmwj4YO6x86h5D584m0MBrzA7X5o0dPjfgK2/FHuf2miKPUhvyKnxKWdJMVWXXfQpy2e24bzEzXJGMUKuSoSTap3qWE4Iuee2AI+++VafssnHL9O5vvwFL+27zfnBBB888oLOnmu5j6dfwGellgPVMxIj/BxmOo+VLJLeg5E="

install: 
    - MINICONDA_URL="https://repo.continuum.io/miniconda"
    - MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    - wget "${MINICONDA_URL}/${MINICONDA_FILE}"
    - bash $MINICONDA_FILE -b
    - export PATH=/Users/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda install --yes conda-build jinja2 anaconda-client
script:
    - ./travis_build.sh

after_success:
    - cp /Users/travis/miniconda3/conda-bld/osx-64/*.tar.bz2 .
    - ls *.tar.bz2
#    - anaconda -t $TOKEN upload *.tar.bz2
